<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net481</TargetFramework>
    <AssemblyName>APISharedTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="APIShared"><HintPath>..\..\APIShared\BepInEx\plugins\APIShared_Serp\APIShared.dll</HintPath><Private>true</Private></Reference>
    <Compile Include="..\..\Shared\Runtime\Persistence\DependencyFreeJson.cs" Link="DependencyFreeJson.cs" />
  </ItemGroup>
</Project>
