<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MapParser.Core</RootNamespace>
    <AssemblyName>MapParser.Core</AssemblyName>
  </PropertyGroup>
</Project>
