<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>AIVPlacementLobby.Core</RootNamespace>
    <AssemblyName>AIVPlacementLobby.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\AIVPlacement\AIVPlacement.Core\AIVPlacement.Core.csproj" />
  </ItemGroup>
</Project>
