namespace SHCDESE.Interop
{
    internal enum eChimps : ushort
    {
        CHIMP_TYPE_PEASANT = 1,
        CHIMP_TYPE_HUNTER = 6,
        CHIMP_TYPE_ARCHER = 22,
        CHIMP_TYPE_XBOWMAN = 23,
        CHIMP_TYPE_SPEARMAN = 24,
        CHIMP_TYPE_PIKEMAN = 25,
        CHIMP_TYPE_MACEMAN = 26,
        CHIMP_TYPE_SWORDSMAN = 27,
        CHIMP_TYPE_KNIGHT = 28,
        CHIMP_TYPE_ENGINEER = 30,
        CHIMP_TYPE_MONK = 37,
        CHIMP_TYPE_ARCHER_debug = 38,
        CHIMP_TYPE_CATAPULT = 39,
        CHIMP_TYPE_TREBUCHET = 40,
        CHIMP_TYPE_MANGONEL = 41,
        CHIMP_TYPE_BALLISTA = 61,
        CHIMP_TYPE_ARAB_BOW = 70,
        CHIMP_TYPE_ARAB_SLINGER = 72,
        CHIMP_TYPE_ARAB_HORSEMAN = 74,
        CHIMP_TYPE_ARAB_GRENADIER = 76,
        CHIMP_TYPE_ARAB_BALLISTA = 77,
        CHIMP_TYPE_BEDOUIN_HEALER = 79,
        CHIMP_TYPE_BEDOUIN_EUNUCH = 80,
        CHIMP_TYPE_BEDOUIN_AMBUSHER = 81,
        CHIMP_TYPE_BEDOUIN_SKIRMISHER = 82,
        CHIMP_TYPE_BEDOUIN_HEAVY_CAMEL = 83,
        CHIMP_TYPE_BEDOUIN_SAPPER = 84,
        CHIMP_TYPE_BEDOUIN_DEMOLISHER = 85,
    }
}
