<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GameDir)' == ''">
    <GameDir>E:\ProgrammeE\Steam\steamapps\common\Stronghold Crusader Definitive Edition</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Iced"><HintPath>$(GameDir)\BepInEx\plugins\000shcdese\Iced.dll</HintPath></Reference>
    <Reference Include="RedBird.Abstractions"><HintPath>$(GameDir)\BepInEx\plugins\000shcdese\RedBird.Abstractions.dll</HintPath></Reference>
    <Reference Include="RedBird.Core"><HintPath>$(GameDir)\BepInEx\plugins\000shcdese\RedBird.Core.dll</HintPath></Reference>
    <Reference Include="RedBird.X64"><HintPath>$(GameDir)\BepInEx\plugins\000shcdese\RedBird.X64.dll</HintPath></Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions"><HintPath>$(GameDir)\BepInEx\plugins\000shcdese\Microsoft.Extensions.Logging.Abstractions.dll</HintPath></Reference>
  </ItemGroup>
</Project>
